apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethereum-node
  labels:
    app: ethereum
spec:
  replicas: 1
  selector:
    matchlabels:
      app: ethereum
  template:
    metadata:
      labels:
        app: ethereum
    spec:
      containers:
      - name: geth
        image: ethereum/client-go:stable
        args: 
          - "--networkid=1234"
          - "--http"
          - "--http.addr=0.0.0.0"
          - "--http.port=8545"
          - "--http.api=eth,net,web3,personal"
        ports:
        - containerPort: 8545
        - containerPort: 30303
        volumeMounts:
        -name: data
        mountPath: /data
      volumes:
      - name: data
        emptyDir: {}